### PR TITLE
add spiritswap fees

### PR DESCRIPTION
**Pull request by dtmkeng**

### CODE REVIEW

**Comment by dtmkeng** [comment]
V2 vAMM fee structure: 
Of the NEW 0.18% fee collected: 
25 % will be distributed to “Base Fee” (inSPIRIT holders) 
25% will be distributed to the "Protocol Fee"
50% will be distributed to "Vote Fee" (inSPIRIT holders gauge specific)

**Comment by wrappor** [comment]
i'm guessing we also want to include the stableswap fees as well? seems like those are a little different https://docs.spiritswap.finance/spiritswap-v2/core-features/protocol-fees/stable-swap-fees-0.04-customizable-fees

**Comment by dtmkeng** [comment]
I'd better add it. will fix it

**Comment by dtmkeng** [comment]
done!

**Comment by wrappor** [comment]
> done!

i think we would want to separate stableswap volume from vAMM volume, and then multiply the fees per volume. Might be a bit tricky since we won't be able to directly use the existing dex adapter

**Comment by dtmkeng** [comment]
> 
first we should fix adapter dex volume ?

**Comment by wrappor** [comment]
> > 
> 
> first we should fix adapter dex volume ?

yeah, probably makes sense to break out the dexVolume adapter into separate portions - i dont think it's necessarily crucial to track this in volume adapters versus fees since they're different based on volume type. 
this might be a case where you have to write customized code to separate the volume types

cc @0xtawa

**Comment by 0xtawa** [comment]
moved to https://github.com/DefiLlama/fees-adapters

**Pull request closed without merging**
